// <auto-generated />
using System;
using FinanceAdvisor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceAdvisor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330103322_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceAdvisor.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1556m,
                            Category = 0,
                            Date = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Swiggy Order",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1763m,
                            Category = 0,
                            Date = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zomato Dinner",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 4346m,
                            Category = 0,
                            Date = new DateTime(2026, 2, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Swiggy Order",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2259m,
                            Category = 0,
                            Date = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zomato Dinner",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2901m,
                            Category = 0,
                            Date = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zomato Dinner",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 764m,
                            Category = 1,
                            Date = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Metro Pass",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 3481m,
                            Category = 1,
                            Date = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uber Ride",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 5788m,
                            Category = 1,
                            Date = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Metro Pass",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 831m,
                            Category = 1,
                            Date = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fuel",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 7296m,
                            Category = 1,
                            Date = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fuel",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 811m,
                            Category = 2,
                            Date = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Movie Tickets",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = 6657m,
                            Category = 2,
                            Date = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Netflix",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            Amount = 6538m,
                            Category = 2,
                            Date = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Concert",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            Amount = 697m,
                            Category = 3,
                            Date = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electricity Bill",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            Amount = 5198m,
                            Category = 3,
                            Date = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electricity Bill",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            Amount = 6293m,
                            Category = 3,
                            Date = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Internet Bill",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            Amount = 833m,
                            Category = 5,
                            Date = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clothing",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            Amount = 880m,
                            Category = 5,
                            Date = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flipkart Order",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            Amount = 5213m,
                            Category = 5,
                            Date = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Amazon Purchase",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            Amount = 2505m,
                            Category = 0,
                            Date = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Swiggy Order",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            Amount = 1032m,
                            Category = 0,
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zomato Dinner",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            Amount = 6483m,
                            Category = 0,
                            Date = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zomato Dinner",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            Amount = 4246m,
                            Category = 0,
                            Date = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Swiggy Order",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            Amount = 523m,
                            Category = 1,
                            Date = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uber Ride",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            Amount = 759m,
                            Category = 1,
                            Date = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Metro Pass",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            Amount = 3958m,
                            Category = 1,
                            Date = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ola Cab",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            Amount = 3295m,
                            Category = 2,
                            Date = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Netflix",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            Amount = 6442m,
                            Category = 2,
                            Date = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Concert",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 29,
                            Amount = 2730m,
                            Category = 2,
                            Date = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Spotify",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 30,
                            Amount = 645m,
                            Category = 3,
                            Date = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Water Bill",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 31,
                            Amount = 2996m,
                            Category = 3,
                            Date = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mobile Recharge",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 32,
                            Amount = 1273m,
                            Category = 3,
                            Date = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Internet Bill",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 33,
                            Amount = 6320m,
                            Category = 3,
                            Date = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electricity Bill",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 34,
                            Amount = 2117m,
                            Category = 3,
                            Date = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mobile Recharge",
                            IsRecurring = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 35,
                            Amount = 6246m,
                            Category = 5,
                            Date = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clothing",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 36,
                            Amount = 2671m,
                            Category = 5,
                            Date = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clothing",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 37,
                            Amount = 5381m,
                            Category = 5,
                            Date = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Amazon Purchase",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 38,
                            Amount = 7467m,
                            Category = 5,
                            Date = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Amazon Purchase",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 39,
                            Amount = 2490m,
                            Category = 5,
                            Date = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Amazon Purchase",
                            IsRecurring = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 40,
                            Amount = 4942m,
                            Category = 5,
                            Date = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flipkart Order",
                            IsRecurring = false,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FinanceAdvisor.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mustafeez@demo.com",
                            FullName = "Mustafeez Khan",
                            PasswordHash = "KsR1eALd+pVA8oWwTXuigrVfIGuaRwDBEBDrxBDNtKs="
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "barclays@demo.com",
                            FullName = "Barclays Demo",
                            PasswordHash = "KsR1eALd+pVA8oWwTXuigrVfIGuaRwDBEBDrxBDNtKs="
                        });
                });

            modelBuilder.Entity("FinanceAdvisor.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FinanceAdvisor.Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceAdvisor.Domain.Entities.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
